# 不指定数据连接池的时候默认使用tomcat的数据库连接池
spring:
  datasource:
    username: root
    password: 123
    url: jdbc:mysql://localhost:3306/test
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
  redis:
    host: 192.168.3.15

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations:
    - classpath:mapper/*.xml


logging:
  level: debug

debug: true
